"""
Prompts Package
=============
All master prompts for each agent.
Import prompts from here.
"""

# Researcher Prompts
from prompts.researcher import (
    RESEARCHER_SYSTEM_PROMPT,
    LEGAL_QA_PROMPT,
    ANALYSIS_PROMPT,
    PATHFINDER_PROMPT,
    IPC_TO_BNS_MAP,
    CRPC_TO_BNSS_MAP,
    UNCERTAINTY_PROMPT,
    RESPONSE_FORMAT,
)

# Drafter Prompts
from prompts.drafter import (
    DRAFTER_SYSTEM_PROMPT,
    LEGAL_NOTICE_PROMPT,
    CHEQUE_BOUNCE_NOTICE_PROMPT,
    EMPLOYMENT_NOTICE_PROMPT,
    FIR_COMPLAINT_PROMPT,
    RENTAL_AGREEMENT_PROMPT,
    FIELD_VALIDATION_PROMPT,
    DRAFT_RESPONSE_FORMAT,
)

# Reviewer Prompts
from prompts.reviewer import (
    REVIEWER_SYSTEM_PROMPT,
    CONTRACT_EVALUATION_PROMPT,
    LEGAL_SCRUTINY_PROMPT,
    LIMITATION_CHECK_PROMPT,
    DOCUMENT_VALIDATION_PROMPT,
    CLAUSE_ANALYSIS_PROMPT,
    RED_FLAGS_PROMPT,
    VETO_CHECK_PROMPT,
    REVIEW_RESPONSE_FORMAT,
)

# Binary Gate
from prompts.binary_gate import BINARY_GATE_PROMPT

__all__ = [
    "BINARY_GATE_PROMPT",

    # Researcher
    "RESEARCHER_SYSTEM_PROMPT",
    "LEGAL_QA_PROMPT",
    "ANALYSIS_PROMPT", 
    "PATHFINDER_PROMPT",
    "IPC_TO_BNS_MAP",
    "CRPC_TO_BNSS_MAP",
    "UNCERTAINTY_PROMPT",
    "RESPONSE_FORMAT",
    
    # Drafter
    "DRAFTER_SYSTEM_PROMPT",
    "LEGAL_NOTICE_PROMPT",
    "CHEQUE_BOUNCE_NOTICE_PROMPT",
    "EMPLOYMENT_NOTICE_PROMPT",
    "FIR_COMPLAINT_PROMPT",
    "RENTAL_AGREEMENT_PROMPT",
    "FIELD_VALIDATION_PROMPT",
    "DRAFT_RESPONSE_FORMAT",
    
    # Reviewer
    "REVIEWER_SYSTEM_PROMPT",
    "CONTRACT_EVALUATION_PROMPT",
    "LEGAL_SCRUTINY_PROMPT",
    "LIMITATION_CHECK_PROMPT",
    "DOCUMENT_VALIDATION_PROMPT",
    "CLAUSE_ANALYSIS_PROMPT",
    "RED_FLAGS_PROMPT",
    "VETO_CHECK_PROMPT",
    "REVIEW_RESPONSE_FORMAT",
]